# Generated by Django 5.2.6 on 2025-09-20 17:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('policy_number', models.CharField(max_length=64, unique=True)),
                ('customer_id', models.UUIDField()),
                ('product_code', models.CharField(max_length=50)),
                ('coverage_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('premium_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('premium_frequency', models.CharField(default='annual', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('term_years', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('lapsed', 'Lapsed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=20)),
                ('underwriting_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('agent_id', models.UUIDField(blank=True, null=True)),
                ('add_ons', models.JSONField(blank=True, null=True)),
                ('nominees', models.JSONField(blank=True, null=True)),
                ('next_premium_due_date', models.DateField(blank=True, null=True)),
                ('grace_period_end_date', models.DateField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['policy_number'], name='policies_po_policy__a03f9f_idx'), models.Index(fields=['customer_id'], name='policies_po_custome_0a4e6a_idx'), models.Index(fields=['status'], name='policies_po_status_83d281_idx')],
            },
        ),
        migrations.CreateModel(
            name='PremiumPayment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_ref', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='success', max_length=20)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='policies.policy')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
