# Generated by Django 5.2.6 on 2025-09-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='policy_number',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
